### PR TITLE
Added registration of ReqnrollFeatureFiles for Rider/ReSharper Build

### PR DESCRIPTION
**Pull request by Runnerok**
### 🤔 What's changed?

Added registration of custom "ReqnrollFeatureFiles" type in Reqnroll.Tools.MsBuild.Generation.props

Per [suggestion](https://github.com/reqnroll/Reqnroll.Rider/issues/1#issuecomment-2050945048) from @Socolin

### ⚡️ What's your motivation? 
#57 and [issue](https://github.com/reqnroll/Reqnroll.Rider/issues/1) in Reqnroll.Rider

### 🏷️ What kind of change is this?

- :bug: Bug fix (non-breaking change which fixes a defect)

### ♻️ Anything particular you want feedback on?

In my understanding this change shouldn't break anything for Visual Studio, but if i'm not correct please let me know

----

*This text was originally taken from the [template of the Cucumber project](https://github.com/cucumber/.github/blob/main/.github/PULL_REQUEST_TEMPLATE.md), then edited by hand. [You can modify the template here.](https://github.com/reqnroll/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

### CODE REVIEW

**Comment by ajeckmans** [comment]
Seems like a reasonable change.

**Review by Code-Grump — APPROVED** [review]

**Review by gasparnagy — COMMENTED** [review]
This is a great idea!

I have two questions:

1. Just to confirm: did you manually double checked that using the nuget package containing this in Rider fixes the problem?

2. Are you aware of any MsBuild variable that is set when the project is loaded in Rider? Becuase in this case we could put this to a conditional section, so we definitely not impact anything else.

**Comment by Runnerok** [comment]
> 1. Just to confirm: did you manually double checked that using the nuget package containing this in Rider fixes the problem?

Yes, after applying this change and rebuilding the project existing and newly added `.feature` files are visible and recognized as `ReqnrollFeatureFiles` in file properties
image

Current workaround for this issue from [documentation](https://docs.reqnroll.net/latest/installation/setup-ide.html#setup-rider):
```
<ItemGroup>
    <Content Include="**/*.feature"/>
</ItemGroup>
```
will need to be removed from `.csproj` 

> 2. Are you aware of any MsBuild variable that is set when the project is loaded in Rider? Becuase in this case we could put this to a conditional section, so we definitely not impact anything else.

Unfortunately, I am not aware of such variable, but according to [MSBuild documentation](https://learn.microsoft.com/en-us/visualstudio/msbuild/visual-studio-integration-msbuild?view=vs-2022#additional-build-actions) in Visual Studio this change does pretty much the same thing of enabling items of that type to be visible in Solution Explorer and Build Actions dropdown, so should be safe

**Review by gasparnagy — CHANGES_REQUESTED** [review]
Could you please add a line to the Improvements section of the CHANGELOG.md and add your github handle to the Contributors of this release section?

**Review by gasparnagy — APPROVED** [review]
Thx!

**Comment by gasparnagy** [comment]
@Runnerok Thank you for the contribution! According to our [guidelines](https://github.com/orgs/reqnroll/discussions/67) I have invited you to the Reqnroll [contributors team](https://github.com/orgs/reqnroll/teams/contributors/members). Congrats! 🎉 If you accept it, you will be able to make pull requests easier in the future.

You are also welcome on our discord server: https://go.reqnroll.net/discord-invite

**Pull request merged**
