### PR TITLE
Replacing VSWhere with MSBuild.Locator

### PR DESCRIPTION
**Pull request by Tiberriver256**
This should expand MSBuild discovery to include dotnet SDK installations allowing developers to use other tooling besides Visual Studio (i.e., JetBrains/VSCode/etc.)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ ] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Performance improvement
- [ ] Refactoring (so no functional change)
- [x] Other (docs, build config, etc)

### CODE REVIEW

**Comment by Tiberriver256** [comment]
@ajeckmans / @gasparnagy 

I had a chance to make a PR based on what was discussed in #74. 

* We're still using msbuild.exe
* We've replaced VSWhere with [MSBuild.Locator](https://github.com/microsoft/MSBuildLocator) to expand the MSBuild search to include dotnet SDK installations as a potential location

All the CI tests pass, but at the moment, I believe the CI tests only run a small portion of the tests, so there's a potential for breakage here.

I am also not a JetBrains user, so if you could try it out for us, @ajeckmans, and see if it works better for you locally, that would be awesome.

**Comment by gasparnagy** [comment]
Thank you @Tiberriver256! This looks good. If @ajeckmans sends an OK signal, we should squash & merge this.

Technical side note: In general, I suggest that the ones who are already in the contributors or the core team groups to do the PRs from branches of this repo directly (without forking), because that way it is easier for others (like in this case @ajeckmans) to try it out or even making small fixes.

**Comment by Tiberriver256** [comment]
Sounds good @gasparnagy. I'll plan on using branches moving forward. Let me know if you want me to close this PR and reopen a new one from a branch.

**Comment by gasparnagy** [comment]
@Tiberriver256 not at all. Was just a comment for the future.

**Comment by ajeckmans** [comment]
I'll not be able to check this today. It will have to wait till tomorrow. 
I'm also fine with just merging this. If it works for the CI and building in Visual Studio at least it won't make things worse :)

**Pull request merged**
