### PR TITLE
Improve parameter type naming for generic types

### PR DESCRIPTION
**Pull request by olegKoshmeliuk**
### 🤔 What's changed?

Changed RuntimeBindingType.FullName behavior for generic types.
Before it was simple Type.FullName which is not working good for generic and nullable types.
Now it's using custom logic to provide better value for autocomplete for generic types.

Example new placeholders:
image

### ⚡️ What's your motivation? 

Current behavior : 
* `List<string>` => System.Collections.Generic.List`1[[System.String, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
* `int?` => System.Nullable`1[[System.Int32, System.Private.CoreLib, Version=8.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]

That is resulting bad autocomplete hints in VS Plugin. (it's using FullName as a Placeholder)
This PR will change autocomplete steps in VS to be more readable.
From placeholder: `[0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]]`
To placeholder: `[List<String>]`

### 🏷️ What kind of change is this?

- :bug: Bug fix (non-breaking change which fixes a defect)

### 📋 Checklist:

- [X] I've changed the behaviour of the code
  - [ ] I have added/updated tests to cover my changes.
- [X] Users should know about my change
  - [X] I have added an entry to the "[vNext]" section of the [**CHANGELOG**](../blob/main/CHANGELOG.md), linking to this pull request & included my GitHub handle to the release contributors list.

----

*This text was originally taken from the [template of the Cucumber project](https://github.com/cucumber/.github/blob/main/.github/PULL_REQUEST_TEMPLATE.md), then edited by hand. [You can modify the template here.](https://github.com/reqnroll/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

### CODE REVIEW

**Comment by olegKoshmeliuk** [comment]
@gasparnagy I open for suggestions. 
I didn't add tests because i did't find best place.  
But if you suggest I can create TestClass or Theory test for FullName getter.

**Comment by gasparnagy** [comment]
@olegKoshmeliuk Thx. Did you check if the VS extension code uses this for anything else than displaying it? Aren't we breaking any backwards compatibility?

**Comment by olegKoshmeliuk** [comment]
Possible breaking this code for generic types: [BindingReflectionExtensions.cs#L15C9-L38C10](https://github.com/reqnroll/Reqnroll/blob/4642769a5a2ec908eaf09401aef63a28bd3481d9/Reqnroll/Bindings/Reflection/BindingReflectionExtensions.cs#L15C9-L38C10) because it's comparing with `Type.FullName`

From what I saw VS extension expects <Namespace>.<Type> format in FullName like in non generic types. [example](https://github.com/reqnroll/Reqnroll.VisualStudio/blob/c4698285f74a6e720b7191efcb1c30158b4e95a0/Reqnroll.VisualStudio/Editor/Completions/StepDefinitionSampler.cs#L57C1-L58C1) so it's mostly a bug fix for VS extension

**Review by gasparnagy — APPROVED** [review]
Thx!

**Pull request merged**
