### PR TITLE
Add DateTimeOffsetValueComparer

### PR DESCRIPTION
**Pull request by cimnine**
### 🤔 What's changed?

Adds a `DateTimeOffsetValueComparer`, fixes https://github.com/reqnroll/Reqnroll/issues/179.

### ⚡️ What's your motivation? 

We mostly use `DateTimeOffset` instead of `DateTime` in our projects.

### 🏷️ What kind of change is this?

- :bug: Bug fix (non-breaking change which fixes a defect)

### 📋 Checklist:

- [x] I've changed the behaviour of the code
  - [x] I have added/updated tests to cover my changes.
- [ ] My change requires a change to the documentation.
  - [ ] I have updated the documentation accordingly.
- [x] Users should know about my change
  - [x] I have added an entry to the "[vNext]" section of the [**CHANGELOG**](../blob/main/CHANGELOG.md), linking to this pull request & included my GitHub handle to the release contributors list.

----

*This text was originally taken from the [template of the Cucumber project](https://github.com/cucumber/.github/blob/main/.github/PULL_REQUEST_TEMPLATE.md), then edited by hand. [You can modify the template here.](https://github.com/reqnroll/.github/edit/main/.github/PULL_REQUEST_TEMPLATE.md)*

### CODE REVIEW

**Comment by gasparnagy** [comment]
@cimnine This makes sense. Could you please check the runtime test failures?

In general it is also worth noting that we did have a *retriever* for `DateTimeOffset`, but not a comparer (I don't know why).

**Comment by cimnine** [comment]
> Could you please check the runtime test failures?

Done.

**Review by gasparnagy — APPROVED** [review]
Thx for the fix!

**Comment by gasparnagy** [comment]
@cimnine Thank you for the contribution! According to our [guidelines](https://github.com/orgs/reqnroll/discussions/67) I have invited you to the Reqnroll [contributors team](https://github.com/orgs/reqnroll/teams/contributors/members). Congrats! 🎉 If you accept it, you will be able to make pull requests easier in the future.

You are also welcome on our discord server: https://go.reqnroll.net/discord-invite

**Pull request merged**
