### PR TITLE
Improve code-behind feature file compilation speed

### PR DESCRIPTION
**Pull request by obligaron**
### 🤔 What's changed?

When generating a Reqnroll project with many feature files, compilation can be improved (times for `BigReqnrollProject` with 500 feature files) from 5.4s to 1.1s:

- original/main 5.4s
- making FixVB RegEx static 5.2s
- don't call VBFix in C# project 2.1s
- cache gherkin dialect (provider) and avoid assembly resource loads 1.2s
- avoid enum boxing 1.1s

This PR reduces compilation time by 80% (for large projects).

### ⚡️ What's your motivation? 

Trying to improve the compilation time of Reqnroll projects.

### 🏷️ What kind of change is this?

- :bank: Refactoring/debt/DX (improvement to code design, tooling, etc. without changing behaviour)

### ♻️ Anything particular you want feedback on?

I used the 

### 📋 Checklist:

- [x] Users should know about my change
  - [x] I have added an entry to the "[vNext]" section of the [**CHANGELOG**](../blob/main/CHANGELOG.md), linking to this pull request & included my GitHub handle to the release contributors list.

### CODE REVIEW

**Review by gasparnagy — CHANGES_REQUESTED** [review]
Wow! Super! You are great!

Could you please add the PR number to the end of the changelog line?

**Comment by obligaron** [comment]
I added the PR number 🙂

**Review by gasparnagy — APPROVED** [review]
Thx!

**Comment by gasparnagy** [comment]
Released in 2.3.0: https://github.com/reqnroll/Reqnroll/releases/tag/v2.3.0

**Pull request merged**
