### PR TITLE
supported DataRow attributes with Scenario Outline and MsTest #48

### PR DESCRIPTION
**Pull request by livioc**
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue).
- [ x] New feature (non-breaking change which adds functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected).
- [ ] Performance improvement
- [ ] Refactoring (so no functional change)
- [ ] Other (docs, build config, etc)

## Checklist:

- [ x] I've added tests for my code. (most of the time mandatory)
- [ x] I have added an entry to the changelog. (mandatory)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by gasparnagy** [comment]
@livioc do you have any guess why the MsTest specs fail? I see some NullRef exceptions, but don't really understand why.

**Comment by livioc** [comment]
> @livioc do you have any guess why the MsTest specs fail? I see some NullRef exceptions, but don't really understand why.

No, I think is something related to Outline Scenario that is broken because now also mstest provider generates 1 test for example case. I have same problems running the tests locally to understand how they work (I need to install all the required runtimes and replace the specflow vs plugin with roqnroll) so I'm waiting to have some free time for it :(

**Comment by gasparnagy** [comment]
@livioc ok. I will check it.

**Comment by gasparnagy** [comment]
Moved over to a main repo branch as #54 . Closing this one.

**Pull request closed without merging**
